In [1]:
import pandas as pd

In [2]:
house_transactions = pd.read_csv('house_transactions.csv', parse_dates=[2])
house_transactions.dropna(subset=['ticker'], inplace=True)
house_transactions = house_transactions[house_transactions['ticker'] != '--']
house_transactions = house_transactions[house_transactions['type'] != 'exchange']
house_transactions = house_transactions[house_transactions['transaction_date'].dt.year == 2020]
house_transactions.rename(columns={'ticker': 'ticker_original', 'type': 'type_detailed'}, inplace=True)
original_tickers = house_transactions['ticker_original']
house_transactions['ticker'] = [t.split(".")[0] if '.' in t else t for t in original_tickers]
house_transactions['share_class'] = [t.split(".")[1] if '.' in t else None for t in original_tickers]
house_transactions['type'] = house_transactions.apply(lambda row: 'Purchase' if row['type_detailed'] == 'purchase' else 'Sale', axis=1)
house_transactions['representative'] = house_transactions['representative'].str.slice(5)
house_transactions.sort_values(by='transaction_date', inplace=True)

house_transactions

,disclosure_year,disclosure_date,transaction_date,owner,ticker_original,asset_description,type_detailed,amount,representative,district,ptr_link,cap_gains_over_200_usd,ticker,share_class,type
1967,2020,01/13/2020,2020-01-02,NaN,NEE,"NextEra Energy, Inc.",sale_full,"$50,001 - $100,000",Debbie Dingell,MI12,https://disclosures-clerk.house.gov/public_dis...,True,NEE,None,Sale
9920,2020,02/07/2020,2020-01-02,--,XOM,Exxon Mobil Corporation,sale_full,"$1,001 - $15,000",Nicholas Van Taylor,TX03,https://disclosures-clerk.house.gov/public_dis...,False,XOM,None,Sale
9262,2020,01/31/2020,2020-01-02,--,BABA,Alibaba Group Holding Limited American Deposit...,sale_partial,"$1,001 - $15,000",James R. Langevin,RI02,https://disclosures-clerk.house.gov/public_dis...,False,BABA,None,Sale
4504,2020,01/06/2020,2020-01-02,NaN,AAPL,Apple Inc.,purchase,"$15,001 - $50,000",Bob Gibbs,OH07,https://disclosures-clerk.house.gov/public_dis...,False,AAPL,None,Purchase
10012,2020,01/10/2020,2020-01-02,NaN,RHHBY,Roche Holdings AG Basel American Depositary Sh...,purchase,"$1,001 - $15,000",Mikie Sherrill,NJ11,https://disclosures-clerk.house.gov/public_dis...,False,RHHBY,None,Purchase
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,2021,01/13/2021,2020-12-31,self,VIAC,ViacomCBS Inc. - Class B,sale_full,"$1,001 - $15,000",Debbie Dingell,MI12,https://disclosures-clerk.house.gov/public_dis...,False,VIAC,None,Sale
850,2021,01/13/2021,2020-12-31,NaN,DIS,Walt Disney Company,sale_partial,"$15,001 - $50,000",Debbie Dingell,MI12,https://disclosures-clerk.house.gov/public_dis...,False,DIS,None,Sale
5147,2021,01/11/2021,2020-12-31,NaN,ADBE,Adobe Inc,purchase,"$1,001 - $15,000",Gilbert Cisneros,CA39,https://disclosures-clerk.house.gov/public_dis...,False,ADBE,None,Purchase
553,2020,02/10/2021,2020-12-31,NaN,OHI,Omega healthcare REIT Investors,sale_full,"$15,001 - $50,000",Billy Long,MO07,https://disclosures-clerk.house.gov/public_dis...,False,OHI,None,Sale
5145,2021,01/11/2021,2020-12-31,NaN,V,"Visa, Inc. (U.S. Trust Holdings)",purchase,"$1,001 - $15,000",Gilbert Cisneros,CA39,https://disclosures-clerk.house.gov/public_dis...,False,V,None,Purchase

In [3]:
# f = open("house_tickers.txt", "w")
# f.write('\n'.join(house_transactions['ticker'].unique()))
# f.close()

In [4]:
house_stocks = pd.read_csv('house_stocks.csv', parse_dates=[1])
house_stocks

/home/hannahwang/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3155: DtypeWarning: Columns (3,6,13,16) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,PERMNO,date,SHRCD,SICCD,TICKER,COMNAM,SHRCLS,TSYMBOL,HSICCD,BIDLO,ASKHI,PRC,VOL,RET,OPENPRC,NUMTRD,RETX
0,10104,2019-01-02,11.0,7372,ORCL,ORACLE CORP,NaN,ORCL,7372.0,44.45000,45.34000,45.22000,14320441.0,0.00155,44.48000,NaN,0.00155
1,10104,2019-01-03,11.0,7372,ORCL,ORACLE CORP,NaN,ORCL,7372.0,44.41000,45.50000,44.78000,19868713.0,-0.00973,44.75000,NaN,-0.00973
2,10104,2019-01-04,11.0,7372,ORCL,ORACLE CORP,NaN,ORCL,7372.0,45.25000,46.95000,46.71000,20983953.0,0.0431,45.37000,NaN,0.0431
3,10104,2019-01-07,11.0,7372,ORCL,ORACLE CORP,NaN,ORCL,7372.0,46.47000,48.10500,47.45000,17967907.0,0.015842,46.93000,NaN,0.015842
4,10104,2019-01-08,11.0,7372,ORCL,ORACLE CORP,NaN,ORCL,7372.0,47.20000,48.36000,47.88000,16255688.0,0.009062,47.93000,NaN,0.009062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562915,93436,2020-12-24,11.0,9999,TSLA,TESLA INC,NaN,TSLA,9999.0,641.00000,666.09003,661.77002,22813214.0,0.024444,642.98999,465870.0,0.024444
562916,93436,2020-12-28,11.0,9999,TSLA,TESLA INC,NaN,TSLA,9999.0,660.79999,681.40002,663.69000,32232732.0,0.002901,674.51001,631681.0,0.002901
562917,93436,2020-12-29,11.0,9999,TSLA,TESLA INC,NaN,TSLA,9999.0,655.00000,669.90002,665.98999,22867542.0,0.003465,661.00000,466884.0,0.003465
562918,93436,2020-12-30,11.0,9999,TSLA,TESLA INC,NaN,TSLA,9999.0,668.36029,696.59998,694.78003,42766263.0,0.043229,672.00000,767565.0,0.043229
562919,93436,2020-12-31,11.0,9999,TSLA,TESLA INC,NaN,TSLA,9999.0,691.12000,718.71997,705.66998,49544141.0,0.015674,699.98999,917115.0,0.015674

In [5]:
house_transactions = house_transactions[house_transactions['ticker'].isin(house_stocks['TICKER'].unique())]

In [6]:
index = pd.read_csv('RUSSEL_3000_2020.csv', parse_dates=[0], thousands=r',')
index

          Date     Open     High      Low    Close
0   2020-01-02  1898.47  1906.65  1893.55  1906.50
1   2020-01-03  1898.47  1906.65  1889.50  1894.53
2   2020-01-06  1885.39  1900.99  1883.30  1900.90
3   2020-01-07  1899.05  1900.22  1893.15  1896.01
4   2020-01-08  1896.88  1912.90  1895.99  1905.02
..         ...      ...      ...      ...      ...
248 2020-12-24  2226.15  2229.05  2220.99  2228.63
249 2020-12-28  2234.79  2246.14  2234.79  2240.85
250 2020-12-29  2241.85  2252.76  2228.60  2232.01
251 2020-12-30  2234.63  2244.76  2234.63  2237.76
252 2020-12-31  2237.70  2250.55  2233.09  2248.44

[253 rows x 5 columns]

In [7]:
house = house_transactions.copy()
house.drop(columns=['ticker_original', 'ptr_link'], inplace=True)

In [ ]:
times = {'1d':1, '5d':5, '1m':22}

for i, tr in house.iterrows():
    stock_prices = house_stocks[house_stocks['TICKER'] == tr['ticker']]
    if tr['share_class']:
        stock_prices = stock_prices[stock_prices['SHRCLS'] == tr['share_class']]
    stock_prices = stock_prices[stock_prices['date'] >= tr['transaction_date']]['PRC']
    index_prices = index[index['Date'] >= tr['transaction_date']]['Close']
    for time in times:
        try:
            house.loc[i, 'return_{}'.format(time)] = (stock_prices.iloc[times[time]] / stock_prices.iloc[0] - 1) * (1 if tr['type'] == 'Purchase' else -1)
            house.loc[i, 'return_index_{}'.format(time)] = (index_prices.iloc[times[time]] / index_prices.iloc[0] - 1) * (1 if tr['type'] == 'Purchase' else -1)
            house.loc[i, 'return_abnormal_{}'.format(time)] = house.loc[i, 'return_{}'.format(time)] - house.loc[i, 'return_index_{}'.format(time)]
        except:
            pass

In [ ]:
house

In [ ]:
house_members = pd.read_csv('house_members.csv', index_col=0, parse_dates=[6])
house_members['age'] = 2020 - house_members['born'].dt.year
house_members['years_in_office'] = 2020 - house_members['assumed_office']
house_members

In [ ]:
for h in house['representative'].unique():
    if h not in house_members.index:
        print(h)

In [ ]:
committees = pd.read_excel('house_committees.xlsx')
committees['Committee'] = committees['Committee'].apply(lambda s: s.replace(' ', '_').replace(',', '').replace("'", ''))
committees

In [ ]:
for name in committees['House Member Name'].unique():
    if name not in house_members['name_committee'].unique():
        print(name)

In [ ]:
for com in committees['Committee'].unique():
    house_members[com] = 0

for i, row in house_members.iterrows():
    for com in committees[committees['House Member Name'] == row['name_committee']]['Committee']:
        house_members.loc[i, com] = 1

house_members

In [ ]:
house_returns = house.join(house_members, on='representative')
house_returns

In [ ]:
house_returns.to_csv(path_or_buf='house_returns.csv')